name: 'Takes DR screenshot'
description: 'read the name again'
inputs:
  dr_url:
    description: 'URL to render'
    required: true
  matrix_token:
    description: 'marix token'
    required: true
  matrix_server:
    description: 'matrix home server'
    required: true
  matrix_room:
    description: 'matrix room'
    required: true
  message:
    description: 'message to send to matrix'
    required: true

runs:
  using: composite
  steps:
  - uses: ruby/setup-ruby@v1
    with:
      working-directory: 'server'
      ruby-version: '3.3'
      bundler-cache: true

  - name: 'Start internal server'
    shell: bash
    working-directory: 'server'
    run: 'bin/rackup -p 9292 -D'

  - name: 'Take a screenshot'
    shell: bash
    env:
      DR_BACKEND_URL: ${{ inputs.dr_url }}
    run: "sleep 10 && ruby screen-today.rb"

  - name: 'Upload screenshot'
    uses: actions/upload-artifact@v4
    with:
      name: screen.png
      path: page.png
      retention-days: 7

  - name: 'Post to matrix'
    shell: bash
    run: |
      ./matrix.sh --homeserver="${{ inputs.matrix_server }}" --token="${{ inputs.matrix_token }}" --room='${{ inputs.matrix_room }}' --send "${{ inputs.message }}"
      ./matrix.sh --homeserver="${{ inputs.matrix_server }}" --token="${{ inputs.matrix_token }}" --room='${{ inputs.matrix_room }}' --send --file=./page.png --image
