name: Screenshot

on:
  workflow_dispatch:
  schedule:
    # 6:15 CEST
    - cron: '15 4 * * *'

env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Take a screenshot'
        run: ruby screen-today.rb

      - name: 'Upload screenshot'
        uses: actions/upload-artifact@v2
        with:
          name: screen.png
          path: page.png
          retention-days: 7

      - name: 'Post to #test on custom trigger'
        run: 'curl -F file=@page.png -F"initial_comment=Dobré ráno!" -F channels=C030DNGLEA3 -H "Authorization: Bearer $SLACK_TOKEN" https://slack.com/api/files.upload'
        if: ${{ github.event_name == 'workflow_dispatch' }}

      - name: 'Post to #dobre-rano on schedule'
        run: 'curl -F file=@page.png -F"initial_comment=Dobré ráno!" -F channels=C02U77KAHL1 -H "Authorization: Bearer $SLACK_TOKEN" https://slack.com/api/files.upload'
        if: ${{ github.event_name == 'schedule' }}
