name: Screenshot

on:
  workflow_dispatch:
  schedule:
    # 6:15 CEST Mon-Fri
    - cron: '15 4 * * 1-5'
    # 12:00 CEST Mon-Fri
    - cron: '0 10 * * 1-5'
    # 6:15 CEST Sat-Sun
    - cron: '15 4 * * SAT,SUN'

env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  MATRIX_TEST_HOOK: ${{ secrets.MATRIX_TEST_HOOK }}
  MATRIX_GM_HOOK: ${{ secrets.MATRIX_GM_HOOK }}
  FREEIMAGE_KEY: ${{ secrets.FREEIMAGE_KEY }}

jobs:
  test-morning:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/screenshot
        with:
          dr_url: 'http://localhost:9292/today/good_morning'
          matrix_token: ${{ secrets.MATRIX_TOKEN }}
          matrix_server: 'https://matrix-client.matrix.org'
          matrix_room: '!yjmiWUSqAYlQdTtTcL:matrix.org'
          message: 'Dobré ráno!'

  test-noon:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/screenshot
        with:
          dr_url: 'http://localhost:9292/today/home_alone'
          matrix_token: ${{ secrets.MATRIX_TOKEN }}
          matrix_server: 'https://matrix-client.matrix.org'
          matrix_room: '!yjmiWUSqAYlQdTtTcL:matrix.org'
          message: 'Dobré poledne!'

  test-weekend:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/screenshot
        with:
          dr_url: 'http://localhost:9292/today/weekend'
          matrix_token: ${{ secrets.MATRIX_TOKEN }}
          matrix_server: 'https://matrix-client.matrix.org'
          matrix_room: '!yjmiWUSqAYlQdTtTcL:matrix.org'
          message: 'Krásný víkendový den!'

  schedule-weekday-morning:
    runs-on: ubuntu-20.04
    if: ${{ (github.event.schedule == '15 4 * * 1-5') }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/screenshot
        with:
          dr_url: 'http://localhost:9292/today/good_morning'
          matrix_token: ${{ secrets.MATRIX_TOKEN }}
          matrix_server: 'https://matrix-client.matrix.org'
          matrix_room: '!OOZqZKcQxqhJfuVyGd:matrix.org'
          message: 'Dobré ráno!'

  schedule-weekday-noon:
    runs-on: ubuntu-20.04
    if: ${{ (github.event.schedule == '0 10 * * 1-5') }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/screenshot
        with:
          dr_url: 'http://localhost:9292/today/home_alone'
          matrix_token: ${{ secrets.MATRIX_TOKEN }}
          matrix_server: 'https://matrix-client.matrix.org'
          matrix_room: '!OOZqZKcQxqhJfuVyGd:matrix.org'
          message: 'Dobré poledne!'

  schedule-weekend-morning:
    runs-on: ubuntu-20.04
    if: ${{ (github.event.schedule == '15 4 * * SAT,SUN') }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/screenshot
        with:
          dr_url: 'http://localhost:9292/today/weekend'
          matrix_token: ${{ secrets.MATRIX_TOKEN }}
          matrix_server: 'https://matrix-client.matrix.org'
          matrix_room: '!OOZqZKcQxqhJfuVyGd:matrix.org'
          message: 'Krásný víkendový den!'
